version: '3'
services:
  redis1:
    image: redis
    container_name: redis1
    ports:
      - 6379:6379
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis1.conf:/etc/redis/redis.conf

  redis2:
    image: redis
    container_name: redis2
    ports:
      - 6380:6380
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis2.conf:/etc/redis/redis.conf

  redis3:
    image: redis
    container_name: redis3
    ports:
      - 6381:6381
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis3.conf:/etc/redis/redis.conf
  
  redis4:
    image: redis
    container_name: redis4
    ports:
      - 6382:6382
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis4.conf:/etc/redis/redis.conf

  redis5:
    image: redis
    container_name: redis5
    ports:
      - 6383:6383
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis5.conf:/etc/redis/redis.conf

  redis6:
    image: redis
    container_name: redis6
    ports:
      - 6384:6384
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis6.conf:/etc/redis/redis.conf