version: '3'
services:
  redis1:
    image: redis
    container_name: redis1
    ports:
      - 6379:6379
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis1.conf:/etc/redis/redis.conf

  redis2:
    image: redis
    container_name: redis2
    ports:
      - 6380:6380
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis2.conf:/etc/redis/redis.conf

  redis3:
    image: redis
    container_name: redis3
    ports:
      - 6381:6381
    network_mode: host
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis3.conf:/etc/redis/redis.conf

  sentinel1:
    image: redis
    container_name: sentinel01
    ports:
      - 26379:26379
    network_mode: host
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: sentinel02
    ports:
      - 26380:26380
    network_mode: host
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/etc/redis/sentinel.conf

  sentinel3:
    image: redis
    container_name: sentinel03
    ports:
      - 26381:26381
    network_mode: host
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/etc/redis/sentinel.conf